### ISSUE TITLE
Create Nano versions of SGIE model configs

### ISSUE THREAD

**Issue by rjhowell44** [canammex-tech/deepstream-services-library#132]

**Comment by Sscsmatrix** [comment]
@rjhowell44 I added config files for nano.  I verified that everything works and checked them in.  In order to verify, I added a python script called ds_3sgie_test.py.  You can use it via:
python3 ds_3sgie_test.py <video file>
example: python3 ds_3sgie_test.py ../../test/streams/rawBikeFootage.mp4
