### ISSUE TITLE
Add build variant to MakeFile

### ISSUE THREAD

**Issue by rjhowell44** [canammex-tech/deepstream-services-library#2]
Need build option to build obj's into a static lib.  Something like
```
$ make lib
``` 
or whatever approach works best

**Comment by Sscsmatrix** [comment]
I updated the makefile with a make lib variant.  This creates a library called dsl-lib.a.  I verified that the various services are there but I am not sure exactly how you want to use this.  So I am going to commit what I have and then you can review it and I will update it.  This will also help me pipe-clean the issue comment system.

**Comment by rjhowell44** [comment]
Looks great Mike... I'm closing the issue 
I've made a couple of additional changes.
- for development, `./test/catch.hpp` (single header test framework) is now our new `main()`
- `DslMain.cpp` has been archived (now `DslMain.cpp.arc`) and left for reference.
- the default build is now the test build and can be run by calling
```
$ ds-app
```
or, to see all results, passing and failing
```
$ ds-app -s
```
