### ISSUE TITLE
Add Set/Get sync - async attributes to the the Sink API

### ISSUE THREAD

**Issue by rjhowell44** [canammex-tech/deepstream-services-library#318]
@jlerasmus I saw you rpost on the nvidia dev re: [RTSP latency does not work with NVSTREAMMUX](https://forums.developer.nvidia.com/t/rtsp-latency-does-not-work-with-nvstreammux/147525)

I've added two new general Sink services for this, something I thought might need to be done at some point. 

```C
DslReturnType dsl_sink_sync_settings_get(const wchar_t* name, boolean* sync, boolean* async);

DslReturnType dsl_sink_sync_settings_set(const wchar_t* name, boolean sync, boolean async);
```

I'm not sure if the defaults should change, but they can at least be updated now.

**Comment by jlerasmus** [comment]
@rjhowell44, thanks for adding this.  I have been testing with recompiling after setting the flags.

As per my post, I believe there is an issue with `nvstreammux` not respecting the latency.  Maybe you could try out the `gst-launch-1.0` commands and confirm what I am seeing.
