### ISSUE TITLE
Extern "C" all public functions in DslApi.h 

### ISSUE THREAD

**Issue by rjhowell44** [canammex-tech/deepstream-services-library#7]

**Comment by Sscsmatrix** [comment]
Years ago I did this with swig and TCL/TK.  But ctypes looks better since it is part of the standard python install.

**Comment by Sscsmatrix** [comment]
The command below creates a shared library from a static library:
g++ -shared -o dsl-lib.so dsl-lib.a

then from python you can run:
>>>from ctypes import *
and then:
>>>cdll.LoadLibrary("dsl-lib.so")
which loads the library into python.
I am going to create a small library first and see if I can get it working before I test this out with the dsl-lib stuff.
