### ISSUE TITLE
Remove unnecessary make include paths 

### ISSUE THREAD

**Issue by rjhowell44** [canammex-tech/deepstream-services-library#85]

**Comment by rjhowell44** [comment]
@Sscsmatrix I made some changes to the MakeFile
* changed app name  `dsl-test-app`
* removed copy of lib to examples... no longer makes sense with new `dsl.py` wrapper at the root

**Comment by Sscsmatrix** [comment]
@rjhowell44 
Stuff looks good! It was easy to modify my software to use it.
